spring:
  application:
    name: salon-explorer

  datasource:
    url: jdbc:postgresql://localhost:5433/salon_explorer
    username: cem1234
    password: cem1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

app:
  import-data:
    enabled: false
    path: classpath:data/salons_cleaned.json
